/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ovh.homefox.edtimelapse;

import java.io.File;
import javax.swing.JFileChooser;
import ovh.homefox.edtimelapse.dialogs.OptionPanes;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import ovh.homefox.edtimelapse.worker.BaseScreenshotWorker;
import ovh.homefox.edtimelapse.worker.FiniteScreenshotWorker;
import ovh.homefox.edtimelapse.worker.InfiniteScreenshotWorker;
import ovh.homefox.edtimelapse.worker.VideoEncodingWorker;

/**
 *
 * @author aymer
 */
public class EDTimelapse extends javax.swing.JFrame {
    
    OptionPanes optionPanes = new OptionPanes();
    BaseScreenshotWorker bsw;
    VideoEncodingWorker vew;
    long duration;
    long interval;
    
    private final long HOURSTOMS = 3600000;
    private final long MINUTESTOMS = 60000;
    private final long SECONDSTOMS = 1000;
    private final int MINDURATION = 0;
    private final int MININTERVAL = 5000;
    
    /**
     * Creates new form EDTimelapse
     */
    public EDTimelapse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        timelapseProgressBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        durationMinutesSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        durationHoursSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        intervalMinutesSpinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        intervalSecondsSpinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        startProcessingButton = new javax.swing.JButton();
        stopProcessingButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        browseScreenshotsButton = new javax.swing.JButton();
        browseVideoButton = new javax.swing.JButton();
        screenshotPathTextField = new javax.swing.JTextField();
        videoPathTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        videoNameTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fpsTextField = new javax.swing.JTextField();
        encodingProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EDTimelapse");
        setResizable(false);

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        stopButton.setText("Stop");
        stopButton.setEnabled(false);
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        timelapseProgressBar.setStringPainted(true);

        jLabel1.setText("Duration :");

        jLabel2.setText("Interval :");

        durationMinutesSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel3.setText("h");

        durationHoursSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel4.setText("m");

        intervalMinutesSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel5.setText("m");

        intervalSecondsSpinner.setModel(new javax.swing.SpinnerNumberModel(5, 5, 59, 1));

        jLabel6.setText("s");

        jLabel11.setText("If the duration equals 0, this tool will keep running unti you");

        jLabel12.setText("manually stop it.");

        jLabel13.setText("Keep in mind that this tool will eat your HDD capacity.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timelapseProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(durationHoursSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(intervalMinutesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(durationMinutesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(intervalSecondsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(startButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stopButton))
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(durationHoursSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(durationMinutesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(intervalMinutesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intervalSecondsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(stopButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timelapseProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Screenshots", jPanel1);

        startProcessingButton.setText("Start");
        startProcessingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startProcessingButtonActionPerformed(evt);
            }
        });

        stopProcessingButton.setText("Stop");
        stopProcessingButton.setEnabled(false);
        stopProcessingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopProcessingButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Screenshot path :");

        jLabel8.setText("Video path :");

        browseScreenshotsButton.setText("Browse");
        browseScreenshotsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseScreenshotsButtonActionPerformed(evt);
            }
        });

        browseVideoButton.setText("Browse");
        browseVideoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseVideoButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Video name :");

        jLabel10.setText("FPS :");

        fpsTextField.setText("30");

        encodingProgressBar.setMaximumSize(new java.awt.Dimension(32767, 17));
        encodingProgressBar.setMinimumSize(new java.awt.Dimension(10, 17));
        encodingProgressBar.setPreferredSize(new java.awt.Dimension(146, 17));
        encodingProgressBar.setStringPainted(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encodingProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(videoPathTextField)
                            .addComponent(screenshotPathTextField)
                            .addComponent(videoNameTextField)
                            .addComponent(fpsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(browseScreenshotsButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(browseVideoButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(startProcessingButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopProcessingButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(browseScreenshotsButton)
                    .addComponent(screenshotPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(browseVideoButton)
                    .addComponent(videoPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(videoNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fpsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startProcessingButton)
                    .addComponent(stopProcessingButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(encodingProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Video", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if(getFormInformations()) {
            activateStop();
            startTakingScreenshots(interval, duration);
        } else {
            optionPanes.displayFormError();
        }
    }//GEN-LAST:event_startButtonActionPerformed

    /**
     * Permet de récupérer les valeurs du formulaire et de les
     * transformer en ms.
     * @return true si tout va bien.
     */
    private boolean getFormInformations(){
        duration = (Integer)durationHoursSpinner.getValue() * HOURSTOMS + (Integer)durationMinutesSpinner.getValue() * MINUTESTOMS;
        interval = (Integer)intervalMinutesSpinner.getValue() * MINUTESTOMS + (Integer)intervalSecondsSpinner.getValue() * SECONDSTOMS;
        return interval >= MININTERVAL && duration >= MINDURATION;
    }
    
    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        bsw.cancel(true);
    }//GEN-LAST:event_stopButtonActionPerformed

    private void startProcessingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startProcessingButtonActionPerformed
        vew = new VideoEncodingWorker(Integer.parseInt(fpsTextField.getText()), 
                screenshotPathTextField.getText(), 
                videoPathTextField.getText(), 
                videoNameTextField.getText(),
                encodingProgressBar,
                this
        );
        activateStopProcessing();
        vew.execute();
    }//GEN-LAST:event_startProcessingButtonActionPerformed

    private void browseScreenshotsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseScreenshotsButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Screenshot browser");
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.setCurrentDirectory(new File(System.getProperty("user.home") + System.getProperty("file.separator")+ "Pictures"));
        if(fc.showOpenDialog(browseScreenshotsButton) == JFileChooser.APPROVE_OPTION){
            screenshotPathTextField.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_browseScreenshotsButtonActionPerformed

    private void browseVideoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseVideoButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Video browser");
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.setCurrentDirectory(new File(System.getProperty("user.home") + System.getProperty("file.separator")+ "Videos"));
        if(fc.showOpenDialog(browseVideoButton) == JFileChooser.APPROVE_OPTION){
            videoPathTextField.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_browseVideoButtonActionPerformed

    private void stopProcessingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopProcessingButtonActionPerformed
        vew.cancel(true);
    }//GEN-LAST:event_stopProcessingButtonActionPerformed

    /**
     * Fonction de lancement des timers pour la prise de screenshots.
     * @param timeBetweenEachScreenshot Durée entre chaque screenshot, en ms.
     * @param globalLength Durée globale de la capture, en ms. Si la valeur est à 0, la prise s'arrêtera lorsque l'utilisateur le choisira.
     */
    private void startTakingScreenshots(long timeBetweenEachScreenshot, long globalLength){
        if(globalLength == 0) {
            bsw = new InfiniteScreenshotWorker(timeBetweenEachScreenshot, timelapseProgressBar, this);
        } else {
            bsw = new FiniteScreenshotWorker(globalLength, timeBetweenEachScreenshot, timelapseProgressBar, this);
        }
        bsw.execute();
    }
    
    /**
     * Permet d'activer les boutons de démarrage, et de désactiver ceux d'arrêts.
     */
    public void activateStart(){
        startButton.setEnabled(true);
        stopButton.setEnabled(false);
        startProcessingButton.setEnabled(true);
        stopProcessingButton.setEnabled(false);
    }
    
    /**
    * Permet d'activer le bouton d'arrêt de prise, et de désactiver les autres.
    */
    public void activateStop(){
        startButton.setEnabled(false);
        stopButton.setEnabled(true);
        startProcessingButton.setEnabled(false);
        stopProcessingButton.setEnabled(false);
    }
    
    /**
     * Permet d'activer le bouton d'arrêt d'encodage et de désactiver les autres.
     */
    public void activateStopProcessing(){
        startButton.setEnabled(false);
        stopButton.setEnabled(false);
        startProcessingButton.setEnabled(false);
        stopProcessingButton.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Set system Look & Feel
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException e) {
           java.util.logging.Logger.getLogger(EDTimelapse.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EDTimelapse().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseScreenshotsButton;
    private javax.swing.JButton browseVideoButton;
    private javax.swing.JSpinner durationHoursSpinner;
    private javax.swing.JSpinner durationMinutesSpinner;
    private javax.swing.JProgressBar encodingProgressBar;
    private javax.swing.JTextField fpsTextField;
    private javax.swing.JSpinner intervalMinutesSpinner;
    private javax.swing.JSpinner intervalSecondsSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField screenshotPathTextField;
    private javax.swing.JButton startButton;
    private javax.swing.JButton startProcessingButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JButton stopProcessingButton;
    private javax.swing.JProgressBar timelapseProgressBar;
    private javax.swing.JTextField videoNameTextField;
    private javax.swing.JTextField videoPathTextField;
    // End of variables declaration//GEN-END:variables
}
